---
apiVersion: v1
kind: Service
metadata:
  name: p2w-evm-relay
  labels:
    app: p2w-evm-relay
spec:
  ports:
    - port: 8081
      name: prometheus
      protocol: TCP
    - port: 4200
      name: rest-api
      protocol: TCP
  clusterIP: None
  selector:
    app: p2w-evm-relay
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: p2w-evm-relay
spec:
  selector:
    matchLabels:
      app: p2w-evm-relay
  serviceName: p2w-evm-relay
  replicas: 1
  template:
    metadata:
      labels:
        app: p2w-evm-relay
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: p2w-evm-relay
          image: p2w-relay
          ports:
            - containerPort: 8081
              name: prometheus
              protocol: TCP
            - containerPort: 4200
              name: rest-api
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/health"
              port: 4200
          command:
            - node
            - lib/index.js
            - "--"
            - "--evm"
          env:
            - name: SPY_SERVICE_HOST
              value: spy:7072
            - name: SPY_SERVICE_FILTERS
              value: '[{"chain_id":1,"emitter_address":"71f8dcb863d176e2c420ad6610cf687359612b6fb392e0642b0ca6b1f186aa3b"}]'
            - name: EVM_NODE_JSON_RPC_URL
              value: "http://eth-devnet:8545"
            - name: EVM_WALLET_MNEMONIC
              value: "myth like bonus scare over problem client lizard pioneer submit female collect"
            - name: EVM_HDWALLET_PATH
              value: "m/44'/60'/0'/0/1" # Use account with idx 1
            - name: EVM_PYTH_CONTRACT_ADDRESS
              value: "0xe982E462b094850F12AF94d21D470e21bE9D0E9C"
            - name: EVM_VERIFY_PRICE_FEEDS
              value: "yes"
            - name: REST_PORT
              value: "4200"
            - name: PROM_PORT
              value: "8081"
            - name: BAL_QUERY_INTERVAL
              value: "60000"
            - name: RETRY_MAX_ATTEMPTS
              value: "4"
            - name: RETRY_DELAY_IN_MS
              value: "250"
            - name: MAX_MSGS_PER_BATCH
              value: "1"
            - name: LOG_LEVEL
              value: debug
