---
apiVersion: v1
kind: Service
metadata:
  name: solana-devnet
  labels:
    app: solana-devnet
spec:
  ports:
    - port: 8899
      name: rpc
      protocol: TCP
    - port: 9900
      name: faucet
      protocol: TCP
  clusterIP: None
  selector:
    app: solana-devnet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solana-devnet
spec:
  selector:
    matchLabels:
      app: solana-devnet
  serviceName: solana-devnet
  replicas: 1
  template:
    metadata:
      labels:
        app: solana-devnet
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: logs
          image: solana-contract
          command:
            - solana
            - logs
            - -u
            - http://localhost:8899
        - name: devnet
          image: solana-contract
          command:
            - /root/.local/share/solana/install/active_release/bin/solana-test-validator
            - --bpf-program
            - Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o
            - /opt/solana/deps/bridge.so
            - --bpf-program
            - gMYYig2utAxVoXnM9UhtTWrt8e7x2SVBZqsWZJeT5Gw # Derived from pyth_program.json
            - /opt/solana/deps/pyth_oracle.so
            - --bpf-program
            - P2WH424242424242424242424242424242424242424
            - /opt/solana/deps/pyth_wormhole_attester.so
            - --bpf-program
            - SMPLVC8MxZ5Bf5EfF7PaMiTCxoBAcmkbM2vkrvMK8ho # copied from squads-mpl/programs/mesh/src/lib.rs
            - /opt/solana/deps/mesh.so
            - --ledger
            - /var/ledger
            - --limit-ledger-size
            - "10000"
            - --log
          ports:
            - containerPort: 8001
              name: gossip
              protocol: UDP
            - containerPort: 8003
              name: tpu
              protocol: UDP
            - containerPort: 8004
              name: tpufwd
              protocol: UDP
            - containerPort: 8000
              name: tvu
              protocol: UDP
            - containerPort: 8002
              name: tvufwd
              protocol: UDP
            - containerPort: 8006
              name: repair
              protocol: UDP
            - containerPort: 8007
              name: serverepair
              protocol: UDP
            - containerPort: 8899
              name: rpc
              protocol: TCP
            - containerPort: 8900
              name: pubsub
              protocol: TCP
            - containerPort: 9900
              name: faucet
              protocol: TCP
          volumeMounts:
            - name: ledger
              mountPath: /var/ledger
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              port: rpc
              path: /health
            periodSeconds: 1
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1000m
              memory: 4Gi
        - name: setup
          image: bridge-client
          command:
            - /usr/src/solana-devnet-setup.sh
          readinessProbe:
            tcpSocket:
              port: 2000
            periodSeconds: 1
            failureThreshold: 300
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 250Mi
      volumes:
        - name: ledger
          emptyDir:
            sizeLimit: 5Gi
        - name: tmp
          emptyDir:
            sizeLimit: 10Mi
