[package]
name = "pyth-sdk-cw"
version = "1.2.1"
authors = ["Pyth Data Foundation"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://pyth.network"
repository = "https://github.com/pyth-network/pyth-crosschain"
description = "Data structures and utilites for the Pyth price oracle"
keywords = [ "pyth", "oracle", "cosmwasm" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
osmosis=[]

[dependencies]
pyth-sdk = "0.7.0"
cosmwasm-std = { version = "1.0.0" }
cosmwasm-schema = "1.1.9"
thiserror = "1.0.20"
