[package]
name = "pyth_lazer_cardano"
version = "0.1.0"
edition = "2024"

[dependencies]
aiken-lang = "1.1.21"
aiken-project = "1.1.21"
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
hex = "0.4.3"
pallas = { version = "0.33.0", features = ["wallet"] }
uplc = "1.1.21"

[lints]
workspace = true
