chains:
  optimism-goerli:
    geth_rpc_addr: https://goerli.optimism.io
    contract_addr: 0x28F16Af4D87523910b843a801454AEde5F9B0459
    reveal_delay_blocks: 0
  avalanche-fuji:
    geth_rpc_addr: https://api.avax-test.network/ext/bc/C/rpc
    contract_addr: 0xD42c7a708E74AD19401D907a14146F006c851Ee3
    reveal_delay_blocks: 0
  eos-evm-testnet:
    geth_rpc_addr: https://api.testnet.evm.eosnetwork.com/
    contract_addr: 0xD42c7a708E74AD19401D907a14146F006c851Ee3
    reveal_delay_blocks: 0
    legacy_tx: true
  arbitrum-goerli:
    geth_rpc_addr: https://arbitrum-goerli.publicnode.com
    contract_addr: 0xd9eAcfFB8e80b7193042499485EF8369b08E85B6
    reveal_delay_blocks: 0
  optimism_sepolia:
    geth_rpc_addr: https://sepolia.optimism.io
    contract_addr: 0x5D289Ad1CE59fCC25b6892e7A303dfFf3a9f7167
    reveal_delay_blocks: 0