services:
  spy:
    # Find latest Guardian images in https://github.com/wormhole-foundation/wormhole/pkgs/container/guardiand
    image: ghcr.io/wormhole-foundation/guardiand:v2.14.8.1
    command:
      - "spy"
      - "--nodeKey"
      - "/node.key"
      - "--spyRPC"
      - "[::]:7072"
      - "--bootstrap"
      - "/dns4/wormhole-mainnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWQp644DK27fd3d4Km3jr7gHiuJJ5ZGmy8hH4py7fP4FP7"
      - "--network"
      - "/wormhole/mainnet/2"
      - "--logLevel"
      - "warn"
  price-service:
    # Find latest price service images https://gallery.ecr.aws/pyth-network/xc-server
    image: public.ecr.aws/pyth-network/xc-server:v3.0.3
    environment:
      SPY_SERVICE_HOST: "spy:7072"
      SPY_SERVICE_FILTERS: |
        [
          {
            "chain_id": 1,
            "emitter_address": "6bb14509a612f01fbbc4cffeebd4bbfb492a86df717ebe92eb6df432a3f00a25"
          },
          {
            "chain_id": 26,
            "emitter_address": "f8cd23c2ab91237730770bbea08d61005cdda0984348f3f6eecb559638c0bba0"
          }
        ]
      REST_PORT: "4200"
      PROM_PORT: "8081"
      READINESS_SPY_SYNC_TIME_SECONDS: "20"
      READINESS_NUM_LOADED_SYMBOLS: "50"
      LOG_LEVEL: warning
      WORMHOLE_CLUSTER: mainnet
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4200/ready",
        ]
      start_period: 20s
    depends_on:
      - spy
  price-pusher:
    build:
      context: .
    # Uncomment this line (and comment out the above lines) to use a prebuilt image. Replace <version>
    # with the latest released image of the price pusher from this repo release page:
    # https://github.com/pyth-network/pyth-crosschain/releases
    # image: public.ecr.aws/pyth-network/xc-price-pusher:v<version>
    restart: always
    command:
      - "--"
      - "evm"
      - "--endpoint"
      # Replace this with RPC endpoint URL for the EVM network.
      - "https://bsc-dataseed2.binance.org"
      - "--mnemonic-file"
      - "/mnemonic"
      - "--pyth-contract-address"
      - "0xd7308b14BF4008e7C7196eC35610B1427C5702EA"
      - "--price-service-endpoint"
      - "http://price-service:4200"
      - "--price-config-file"
      - "/price_config"
    configs:
      - mnemonic
      - price_config
    depends_on:
      price-service:
        condition: service_healthy
configs:
  mnemonic:
    file: ./path/to/mnemonic.txt # Replace this with the path to the mnemonic file
  price_config:
    file: ./price-config.mainnet.sample.yaml # Replace this with the path to the price configuration file
