services:
  spy:
    # Find latest Guardian images in https://github.com/wormhole-foundation/wormhole/pkgs/container/guardiand
    image: ghcr.io/wormhole-foundation/guardiand:v2.14.8.1
    command:
      - "spy"
      - "--nodeKey"
      - "/node.key"
      - "--spyRPC"
      - "[::]:7072"
      - "--bootstrap"
      - "/dns4/wormhole-testnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWAkB9ynDur1Jtoa97LBUp8RXdhzS5uHgAfdTquJbrbN7i"
      - "--network"
      - "/wormhole/testnet/2/1"
      - "--logLevel"
      - "warn"
  price-service:
    # Find latest price service images https://gallery.ecr.aws/pyth-network/xc-server
    image: public.ecr.aws/pyth-network/xc-server:v3.0.0
    environment:
      SPY_SERVICE_HOST: "spy:7072"
      SPY_SERVICE_FILTERS: |
        [
          {
            "chain_id": 1,
            "emitter_address": "f346195ac02f37d60d4db8ffa6ef74cb1be3550047543a4a9ee9acf4d78697b0"
          },
          {
            "chain_id": 26,
            "emitter_address": "a27839d641b07743c0cb5f68c51f8cd31d2c0762bec00dc6fcd25433ef1ab5b6"
          }
        ]
      REST_PORT: "4200"
      PROM_PORT: "8081"
      READINESS_SPY_SYNC_TIME_SECONDS: "20"
      READINESS_NUM_LOADED_SYMBOLS: "50"
      LOG_LEVEL: warning
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4200/ready",
        ]
      start_period: 20s
    depends_on:
      - spy
  price-pusher:
    build:
      context: .
    # Uncomment this line (and comment out the above lines) to use a prebuilt image. Replace <version>
    # with the latest released image of the EVM price pusher from this repo release page:
    # https://github.com/pyth-network/pyth-js/releases
    # image: public.ecr.aws/pyth-network/xc-evm-price-pusher:v<version>
    restart: always
    command:
      - "--"
      - "injective"
      # you can choose to provide all the options here or a path to the config file
      # we are providing a path to the config file
      - "--config"
      - "/command_config"
    configs:
      - command_config
      - mnemonic
      - price_config
    depends_on:
      price-service:
        condition: service_healthy
configs:
  command_config:
    # Replace this with the path to the configuration file. You need to update the paths defined in
    # the config file
    file: ./config.injective.testnet.sample.json
  mnemonic:
    file: ./mnemonic # Replace this with the path to the mnemonic file
  price_config:
    file: ./price-config.testnet.sample.yaml # Replace this with the path to the price configuration file
