[package]
name = "pyth-solana-receiver"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "pyth_solana_receiver"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
mainnet = ["wormhole-anchor-sdk/mainnet"]
devnet = ["wormhole-anchor-sdk/solana-devnet"]

[dependencies]
anchor-lang = "0.28.0"
wormhole-core = { git = "https://github.com/guibescos/wormhole", branch = "reisen/sdk-solana"}
wormhole-solana = { git = "https://github.com/guibescos/wormhole", branch = "reisen/sdk-solana"}
pyth-wormhole-attester-sdk = { path = "../../../../wormhole_attester/sdk/rust" }
pythnet-sdk = { git = "https://github.com/pyth-network/pyth-crosschain", version = "2.0.0", features = ["strum"] }
solana-program = "1.16.20"
hex = "0.4.3"
serde = { version = "1.0.152", features = ["derive"] }
byteorder = "1.4.3"
wormhole-anchor-sdk = {  version = "0.1.0-alpha.2" , default-features = false }
sha3 = "0.10.6"
wormhole-sdk = { git = "https://github.com/wormhole-foundation/wormhole", tag = "v2.17.1" }
serde_wormhole = { git = "https://github.com/wormhole-foundation/wormhole", tag = "v2.17.1"}

[dev-dependencies]
pyth-sdk = "0.8.0"
pyth-sdk-solana = "0.8.0"
solana-program-test = "1.16.20"
solana-sdk = "1.16.20"
tokio = "1.14.1"
bincode = "1.3.3"
libsecp256k1 = "0.7.1"
rand = "0.8.5"
