[package]
name = "pyth-solana-receiver"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "pyth_solana_receiver"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.0"
wormhole-core = { git = "https://github.com/guibescos/wormhole", branch = "reisen/sdk-solana"}
wormhole-solana = { git = "https://github.com/guibescos/wormhole", branch = "reisen/sdk-solana"}
pyth-wormhole-attester-sdk = { path = "../../../../wormhole_attester/sdk/rust" }
solana-program = "1.15.2"

[dev-dependencies]
pyth-sdk = "0.5.0"
pyth-sdk-solana = "0.1.0"
solana-program-test = "=1.15.2"
solana-sdk = "=1.15.2"
tokio = "1.14.1"
bincode = "1.3.3"
