[tool.poetry]
name = "express-relay"
version = "0.10.0"
description = "Utilities for searchers and protocols to interact with the Express Relay protocol."
authors = ["dourolabs"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
web3 = "^6.15.1"
eth_abi = "^4.2.1"
eth_account = "^0.10.0"
httpx = "^0.23.3"
websockets = "^10.0"
asyncio = "^3.4.3"
argparse = "^1.4.0"
pydantic = "^2.6.3"
anchorpy = "^0.20.1"
solana = "^0.34.3"

[tool.poetry.group.dev.dependencies]
black = "^22.3.0"
pyflakes = "^3.2.0"
mypy = "^1.9.0"
anchorpy = {extras = ["cli"], version = "^0.20.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
