[package]
name = "price-service-client"
version = "0.1.0"
authors = ["Pyth Data Foundation"]
edition = "2021"
homepage = "https://pyth.network"
repository = "https://github.com/pyth-network/pyth-crosschain/"
description = "Pyth Hermes Client"
keywords = [ "pyth", "oracle" ]

[dependencies]
async-stream = "0.3.5"
chrono = "0.4.38"
futures-util = "0.3.30"
hermes-types = { git = "https://github.com/aoikurokawa/hermes-types", version = "0.1.0" }
pyth-sdk = { version = "0.8.0" }
reqwest = { version = "0.12.5", features = ["json", "stream"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.39.1", features = ["full"] }
url = "2.5.2"
