[package]
name = "pyth"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.5.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.21.0" }

[lib]

[[target.starknet-contract]]
build-external-contracts = ["openzeppelin::presets::erc20::ERC20"]
