services:
  price-pusher:
    # Use this to build the price pusher from source.
    #
    # Please note that the docker build from source only works in x86_64 platforms
    # and doesn't work on arm platforms (like Apple M1/M2).
    #
    # build:
    #   context: ../..
    #   dockerfile: Dockerfile.node
    #   args:
    #     package: "@pythnetwork/price-pusher"

    # Replace <version> with the latest released image of the price pusher from here:
    # https://gallery.ecr.aws/pyth-network/xc-price-pusher
    image: public.ecr.aws/pyth-network/xc-price-pusher:v<version>
    restart: always
    command:
      - "npm"
      - "run"
      - "start"
      - "--"
      - "evm"
      - "--endpoint"
      # Replace this with RPC endpoint URL for the EVM network.
      - "https://bsc-dataseed2.binance.org"
      - "--mnemonic-file"
      - "/mnemonic"
      # Replace this with the address of the Pyth contract on the EVM network.
      - "--pyth-contract-address"
      - "0xd7308b14BF4008e7C7196eC35610B1427C5702EA"
      - "--price-service-endpoint"
      - "https://hermes.pyth.network" # Replace this with a private Hermes RPC for more reliability
      - "--price-config-file"
      - "/price_config"
    configs:
      - mnemonic
      - price_config
configs:
  mnemonic:
    file: ./path/to/mnemonic.txt # Replace this with the path to the mnemonic file
  price_config:
    file: ./price-config.stable.sample.yaml # Replace this with the path to the price configuration file
