[package]
name = "pyth-solana-receiver-sdk"
version = "0.5.0"
description = "SDK for the Pyth Solana Receiver program"
authors = ["Pyth Data Association"]
repository = "https://github.com/pyth-network/pyth-crosschain"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "pyth_solana_receiver_sdk"


[dependencies]
anchor-lang = ">=0.28.0"
hex = ">=0.4.3"
pythnet-sdk = { path = "../../../pythnet/pythnet_sdk", version = "2.1.0", features = [
    "solana-program",
] }
solana-program = ">=1.16.0, <2.0.0"
