[package]
name = "pyth-solana-receiver-sdk"
version = "1.1.0"
description = "SDK for the Pyth Solana Receiver program"
authors = ["Pyth Data Association"]
repository = "https://github.com/pyth-network/pyth-crosschain"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "pyth_solana_receiver_sdk"


[dependencies]
anchor-lang = "0.32.1"
hex = "0.4.3"
pythnet-sdk = { path = "../../../pythnet/pythnet_sdk", version = "2.3.1", features = [
    "solana-program",
] }

[dev-dependencies]
solana-borsh = "2.2.1" # Needed for borsh0_10 compatibility
