[package]
name = "pyth_lazer"
version = "0.0.0"
edition = "2024.beta"

[addresses]
pyth_lazer = "0x0"
# https://github.com/wormhole-foundation/wormhole/blob/c113791abd5241bc7a23655e3a7475085d51dab7/sui/wormhole/Move.mainnet.toml
wormhole = "0x5306f64e312b581766351c07af79c72fcb1cd25147157fdc2f8ad76de9a3fb6a"

[dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
subdir = "sui/wormhole"
rev = "c113791abd5241bc7a23655e3a7475085d51dab7"

[dev-dependencies]

[dev-addresses]
