[package]
name = "pyth_lazer"
version = "0.0.0"
edition = "2024"

# TODO: Waiting for upstream PR, change to `wormhole-foundation:main` before
# merging.
[dependencies.wormhole]
git = "https://github.com/pyth-network/wormhole.git"
subdir = "sui/wormhole"
rev = "sui-package-update"
