[package]
name = "pyth-push-oracle"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "pyth_push_oracle"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
test-bpf = []

[dependencies]
anchor-lang = { workspace = true }
pythnet-sdk = { path = "../../../../pythnet/pythnet_sdk" }
solana-program = { workspace = true }
byteorder = "1.4.3"
pyth-solana-receiver-sdk = { path = "../../pyth_solana_receiver_sdk"}

[dev-dependencies]
pyth-solana-receiver = { path = "../pyth-solana-receiver", features = ["no-entrypoint"]}
solana-sdk = { workspace = true }
tokio = "1.14.1"
program-simulator = { path = "../../program_simulator" }
wormhole-vaas-serde = { workspace = true }
serde_wormhole = { workspace = true }
common-test-utils = { path = "../../common_test_utils" }
