[package]
name = "Pyth"
version = "0.0.1"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "09b2081498366df936abae26eea4b2d5cafb2788"

[dependencies.Wormhole]
local = "../../../../wormhole/sui/wormhole"

[addresses]
pyth = "0x0"
wormhole = "0x5306f64e312b581766351c07af79c72fcb1cd25147157fdc2f8ad76de9a3fb6a"

[dev-addresses]
pyth = "0x100"
wormhole = "0x200"
