name = "pyth-network/cardano-lazer"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Pyth Lazer integration for Cardano"

[repository]
user = "pyth-network"
project = "pyth-crosschain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
