name: Check Hermes

on:
  pull_request:
    paths: [apps/hermes/**]
  push:
    branches: [main]
    paths: [apps/hermes/**]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-03-26
          components: rustfmt, clippy
          override: true
      - name: Install protoc
        uses: arduino/setup-protoc@v3
      - name: Run executor tests
        run: cargo test --manifest-path ./apps/hermes/Cargo.toml
