on:
  pull_request:
    paths:
      - target_chains/ethereum/contracts/**
      - governance/xc_admin/packages/xc_admin_common/**
  push:
    branches:
      - main
    paths:
      - target_chains/ethereum/contracts/**
      - governance/xc_admin/packages/xc_admin_common/**

name: Ethereum Contract

jobs:
  check:
    name: Foundry tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: target_chains/ethereum/contracts/
    steps:
      - uses: actions/checkout@v3

      - name: Install contract npm dependencies
        run: npm ci

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Forge dependencies
        run: npm run install-forge-deps

      - name: Run tests
        run: forge test -vvv

      - name: Run snapshot
        run: NO_COLOR=1 forge snapshot --match-contract GasBenchmark >> $GITHUB_STEP_SUMMARY
