name: Publish Rust package pyth-lazer-client to crates.io

on:
  push:
    tags:
      - rust-pyth-hermes-client-v*
jobs:
  publish-pyth-hermes-client:
    name: Publish Rust package pyth-hermes-client-rust to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - run: cargo publish --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        working-directory: "apps/hermes/client/rust"
