name: Upload express-relay Python Package to PyPI

on:
  push:
    tags:
      - "python-v*"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade poetry
          cd express_relay/sdk/python/express_relay
          poetry build
      - name: Build and publish
        run: |
          cd express_relay/sdk/python/express_relay
          poetry build
          poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
